"""Grouped component namespaces for more granular imports."""

from docscriptor.components.blocks import (
    Box,
    BulletList,
    Chapter,
    CodeBlock,
    Equation,
    NumberedList,
    Paragraph,
    Section,
    Subsection,
    Subsubsection,
)
from docscriptor.components.generated import (
    CommentsPage,
    FigureList,
    FootnotesPage,
    ReferencesPage,
    TableList,
    TableOfContents,
)
from docscriptor.components.inline import (
    Bold,
    Comment,
    Footnote,
    Hyperlink,
    Italic,
    Math,
    Monospace,
    Text,
    bold,
    code,
    color,
    cite,
    comment,
    footnote,
    italic,
    link,
    math,
    styled,
)
from docscriptor.components.media import Figure, Table, TableCell

__all__ = [
    "Bold",
    "Box",
    "BulletList",
    "Chapter",
    "CodeBlock",
    "Comment",
    "CommentsPage",
    "Equation",
    "Figure",
    "FigureList",
    "Footnote",
    "FootnotesPage",
    "Hyperlink",
    "Italic",
    "Math",
    "Monospace",
    "NumberedList",
    "Paragraph",
    "ReferencesPage",
    "Section",
    "Subsection",
    "Subsubsection",
    "Table",
    "TableCell",
    "TableList",
    "TableOfContents",
    "Text",
    "bold",
    "code",
    "color",
    "cite",
    "comment",
    "footnote",
    "italic",
    "link",
    "math",
    "styled",
]
